# Generated by Django 6.0.5 on 2026-06-01 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('single', 'Private Chat'), ('group', 'Group Chat')], max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('removed', 'Removed'), ('muted', 'Muted')], default='active', max_length=20)),
                ('unread_count', models.IntegerField(default=0)),
                ('last_read_message_id', models.IntegerField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('sticker', 'Sticker'), ('system', 'System')], default='text', max_length=20)),
                ('ciphertext', models.TextField(blank=True, null=True)),
                ('nonce', models.CharField(blank=True, max_length=64, null=True)),
                ('auth_tag', models.CharField(blank=True, max_length=64, null=True)),
                ('algorithm', models.CharField(max_length=50)),
                ('sender_key_version', models.IntegerField(blank=True, null=True)),
                ('receiver_key_version', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('deleted', 'Deleted'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['type'], name='chat_conver_type_857bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='chat_conver_last_me_f07e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['conversation_id'], name='chat_conver_convers_aad361_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['user_id'], name='chat_conver_user_id_142aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['conversation_id', 'status'], name='chat_conver_convers_f806a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_member'),
        ),
        migrations.AddIndex(
            model_name='encryptedmessage',
            index=models.Index(fields=['conversation_id', 'created_at'], name='chat_encryp_convers_cb3e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedmessage',
            index=models.Index(fields=['sender_id'], name='chat_encryp_sender__2df250_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedmessage',
            index=models.Index(fields=['receiver_id'], name='chat_encryp_receive_1a2a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedmessage',
            index=models.Index(fields=['status'], name='chat_encryp_status_1b3d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedmessage',
            index=models.Index(fields=['conversation_id', 'id'], name='chat_encryp_convers_a0f032_idx'),
        ),
    ]
