# Generated by Django 6.0.5 on 2026-06-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='avatar',
            field=models.CharField(blank=True, help_text='Group avatar URL.', max_length=255),
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, help_text='Group chat name; empty for private chats.', max_length=100),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
