# Generated by Django 6.0.5 on 2026-06-02 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_group_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('sticker', 'Sticker'), ('system', 'System')], default='text', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='chat.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciphertext', models.TextField(blank=True, null=True)),
                ('nonce', models.CharField(blank=True, max_length=64, null=True)),
                ('auth_tag', models.CharField(blank=True, max_length=64, null=True)),
                ('algorithm', models.CharField(max_length=50)),
                ('sender_key_version', models.IntegerField(blank=True, null=True)),
                ('receiver_key_version', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='chat.groupmessage')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_message_copies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['conversation_id', 'created_at'], name='chat_groupm_convers_ebf087_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['sender_id'], name='chat_groupm_sender__3839f0_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessagerecipient',
            index=models.Index(fields=['receiver_id', 'created_at'], name='chat_groupm_receive_04ed99_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessagerecipient',
            index=models.Index(fields=['group_message_id'], name='chat_groupm_group_m_18a04c_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmessagerecipient',
            constraint=models.UniqueConstraint(fields=('group_message', 'receiver'), name='unique_group_message_recipient'),
        ),
    ]
