# Generated by Django 6.0.5 on 2026-06-02 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_group_message_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='membership_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='client_message_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='groupmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('sender', 'client_message_id'), name='unique_client_group_message'),
        ),
    ]
