# Generated by Django 6.0.5 on 2026-06-03 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_add_client_message_id_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('activate_user', 'Activate User'), ('deactivate_user', 'Deactivate User'), ('delete_group', 'Delete Group'), ('delete_message', 'Delete Message')], max_length=30)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.IntegerField()),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_id', '-created_at'], name='chat_admino_admin_i_f63463_idx'), models.Index(fields=['action'], name='chat_admino_action_14f6a6_idx')],
            },
        ),
    ]
