# Generated by Django 6.0.5 on 2026-06-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_add_admin_operation_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessagerecipient',
            name='membership_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
