# Generated by Django 6.0.5 on 2026-06-04 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_add_admin_operation_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessageDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group')], max_length=10)),
                ('message_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('busy', 'Busy'), ('offline', 'Offline')], default='online', max_length=20)),
                ('presence_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'Contacts Only'), ('nobody', 'Nobody')], default='everyone', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encryptedmessage',
            name='recalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encryptedmessage',
            name='reply_to_message_id',
            field=models.IntegerField(blank=True, help_text='ID of the message being replied to.', null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='recalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='reply_to_message_id',
            field=models.IntegerField(blank=True, help_text='ID of the message being replied to.', null=True),
        ),
        migrations.AlterField(
            model_name='encryptedmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('deleted', 'Deleted'), ('failed', 'Failed'), ('recalled', 'Recalled')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('recalled', 'Recalled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmessagerecipient',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('recalled', 'Recalled')], default='sent', max_length=20),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['user', 'hidden_at', 'is_pinned'], name='chat_conver_user_id_87c8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['user', 'archived_at'], name='chat_conver_user_id_09cf2b_idx'),
        ),
        migrations.AddField(
            model_name='usermessagedeletion',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_deletions', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='usermessagedeletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usermessagedeletion',
            index=models.Index(fields=['user', 'message_type', 'message_id'], name='chat_userme_user_id_05edf0_idx'),
        ),
        migrations.AddIndex(
            model_name='usermessagedeletion',
            index=models.Index(fields=['conversation', 'user'], name='chat_userme_convers_0d50b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='usermessagedeletion',
            constraint=models.UniqueConstraint(fields=('user', 'message_type', 'message_id'), name='unique_user_message_deletion'),
        ),
    ]
