# Generated by Django 6.0.5 on 2026-06-09 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_add_membership_version_to_group_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='auto_delete_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-delete messages after N seconds. NULL means disabled.', null=True),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='auto_delete_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Per-conversation auto-delete override in seconds.', null=True),
        ),
        migrations.CreateModel(
            name='GroupAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_announcements', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='chat.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', 'is_active'], name='chat_groupa_convers_737c29_idx')],
            },
        ),
    ]
