# Generated by Django 6.0.5 on 2026-06-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_conversation_auto_delete_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
