# Generated by Django 6.0.5 on 2026-06-15 06:42

from django.db import migrations


def backfill_null_metadata(apps, schema_editor):
    """Backfill NULL sender_key_version, receiver_key_version, and
    membership_version on GroupMessageRecipient records so that the
    client-side E2EE decryption does not fail with invalid_metadata.
    """
    GroupMessageRecipient = apps.get_model('chat', 'GroupMessageRecipient')
    Conversation = apps.get_model('chat', 'Conversation')
    UserPublicKey = apps.get_model('accounts', 'UserPublicKey')

    # Bulk-fix membership_version from parent conversation
    updated = GroupMessageRecipient.objects.filter(
        membership_version__isnull=True,
    ).select_related('group_message__conversation')
    count = 0
    for recipient in updated:
        recipient.membership_version = (
            recipient.group_message.conversation.membership_version
        )
        recipient.save(update_fields=['membership_version'])
        count += 1

    # Backfill sender_key_version from sender's active public key
    null_sender = GroupMessageRecipient.objects.filter(
        sender_key_version__isnull=True,
    ).select_related('group_message__sender')
    for recipient in null_sender:
        sender_key = UserPublicKey.objects.filter(
            user=recipient.group_message.sender,
            is_active=True,
        ).first()
        recipient.sender_key_version = (
            sender_key.key_version if sender_key else 1
        )
        recipient.save(update_fields=['sender_key_version'])

    # Backfill receiver_key_version from receiver's active public key
    null_receiver = GroupMessageRecipient.objects.filter(
        receiver_key_version__isnull=True,
    ).select_related('receiver')
    for recipient in null_receiver:
        receiver_key = UserPublicKey.objects.filter(
            user=recipient.receiver,
            is_active=True,
        ).first()
        recipient.receiver_key_version = (
            receiver_key.key_version if receiver_key else 1
        )
        recipient.save(update_fields=['receiver_key_version'])

    # Also backfill zero values (which would also fail requireInteger)
    GroupMessageRecipient.objects.filter(
        sender_key_version=0,
    ).update(sender_key_version=1)
    GroupMessageRecipient.objects.filter(
        receiver_key_version=0,
    ).update(receiver_key_version=1)
    GroupMessageRecipient.objects.filter(
        membership_version=0,
    ).update(membership_version=1)


def reverse_backfill(apps, schema_editor):
    """No-op: we don't revert backfill data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_conversation_muted_until'),
        ('accounts', '0013_general_and_chat_folder_settings'),
    ]

    operations = [
        migrations.RunPython(backfill_null_metadata, reverse_backfill),
    ]
