# Generated by Django 6.0.5 on 2026-06-15 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_chatreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(help_text='UUID for the upload session, used in API URLs.', max_length=36, unique=True)),
                ('client_file_id', models.CharField(help_text='Client-generated UUID, idempotency key.', max_length=64)),
                ('message_kind', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('sticker', 'Sticker')], max_length=20)),
                ('derivative_role', models.CharField(blank=True, choices=[('original', 'Original'), ('thumbnail', 'Thumbnail'), ('preview', 'Preview')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('available', 'Available'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='uploading', max_length=20)),
                ('storage_path', models.CharField(blank=True, help_text='Relative path to merged ciphertext file under MEDIA_ROOT.', max_length=512)),
                ('total_size_bytes', models.PositiveBigIntegerField()),
                ('chunk_size_bytes', models.PositiveIntegerField(default=1048576)),
                ('chunk_count', models.PositiveIntegerField()),
                ('ciphertext_sha256', models.CharField(blank=True, help_text='SHA-256 hex digest of the complete merged ciphertext.', max_length=64)),
                ('encrypted_metadata', models.TextField(blank=True)),
                ('metadata_nonce', models.CharField(blank=True, max_length=64)),
                ('metadata_auth_tag', models.CharField(blank=True, max_length=64)),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat.conversation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('parent_file_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='chat.encryptedfile')),
            ],
        ),
        migrations.AddField(
            model_name='encryptedmessage',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_messages', to='chat.encryptedfile'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_messages', to='chat.encryptedfile'),
        ),
        migrations.CreateModel(
            name='EncryptedFileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('size_bytes', models.PositiveIntegerField()),
                ('offset_bytes', models.PositiveBigIntegerField()),
                ('nonce', models.CharField(max_length=64)),
                ('auth_tag', models.CharField(max_length=64)),
                ('ciphertext_sha256', models.CharField(blank=True, max_length=64)),
                ('storage_path', models.CharField(blank=True, help_text='Temp chunk file path; null after merge into complete file.', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chat.encryptedfile')),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedFileKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_file_key', models.TextField()),
                ('nonce', models.CharField(max_length=64)),
                ('auth_tag', models.CharField(max_length=64)),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('sender_key_version', models.PositiveIntegerField(blank=True, null=True)),
                ('receiver_key_version', models.PositiveIntegerField(blank=True, null=True)),
                ('membership_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='chat.encryptedfile')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='encryptedfile',
            index=models.Index(fields=['conversation', 'status'], name='chat_encryp_convers_272c70_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedfile',
            index=models.Index(fields=['owner', '-created_at'], name='chat_encryp_owner_i_ef892f_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedfile',
            index=models.Index(fields=['upload_id'], name='chat_encryp_upload__3c8f7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='encryptedfile',
            constraint=models.UniqueConstraint(fields=('owner', 'client_file_id'), name='unique_client_file_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='encryptedfilechunk',
            constraint=models.UniqueConstraint(fields=('file', 'chunk_index'), name='unique_file_chunk_index'),
        ),
        migrations.AddConstraint(
            model_name='encryptedfilekey',
            constraint=models.UniqueConstraint(fields=('file', 'holder'), name='unique_file_key_per_holder'),
        ),
    ]
