# Generated by Codex on 2026-06-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_userllmconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_admin', 'Pending Admin Approval'), ('pending_invitee', 'Pending Invitee Approval'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_admin', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations', to='chat.conversation')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_group_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_invitations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_group_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['conversation', 'status'], name='chat_groupi_convers_e418cf_idx'),
                    models.Index(fields=['invitee', 'status'], name='chat_groupi_invitee_f76938_idx'),
                    models.Index(fields=['inviter', 'status'], name='chat_groupi_inviter_1da93f_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(condition=models.Q(('status__in', ['pending_admin', 'pending_invitee'])), fields=('conversation', 'invitee'), name='unique_pending_group_invitation'),
                ],
            },
        ),
    ]
