# Generated by Django 6.0.5 on 2026-06-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_private_message_forward_secrecy'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfilekey',
            name='sender_ephemeral_public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='sender_copy_auth_tag',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='sender_copy_ciphertext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='sender_copy_ephemeral_public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='sender_copy_nonce',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
