# Generated by Django 6.0.5 on 2026-10-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_userllmconfig_assistant_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='sync_sequence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ConversationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField()),
                ('kind', models.CharField(choices=[('message', 'Message')], default='message', max_length=20)),
                ('message_type', models.CharField(blank=True, max_length=20, null=True)),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chat.conversation')),
            ],
            options={
                'indexes': [models.Index(fields=['conversation', 'sequence'], name='chat_conver_convers_2dda5d_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'sequence'), name='unique_conversation_event_sequence')],
            },
        ),
    ]
