# Generated by Django 6.0.5 on 2026-06-02 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact_friendrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPublicKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(help_text='Base64-encoded SPKI public key')),
                ('fingerprint', models.CharField(help_text='SHA-256 hex digest of the SPKI public key', max_length=64, unique=True)),
                ('algorithm', models.CharField(default='ECDH-P256', help_text='Key algorithm identifier', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
