# Generated by Django 6.0.5 on 2026-06-09 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_group_and_groupmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_fingerprint', models.CharField(max_length=64)),
                ('key_version', models.PositiveIntegerField()),
                ('trust_status', models.CharField(choices=[('untrusted', 'Untrusted'), ('trusted', 'Trusted'), ('verified', 'Verified')], default='untrusted', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_trusted_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_trusts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'contact'], name='accounts_ke_user_id_d77452_idx'), models.Index(fields=['contact', 'key_fingerprint'], name='accounts_ke_contact_fcc2fc_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'contact', 'key_fingerprint'), name='unique_key_trust')],
            },
        ),
    ]
