# Generated by Django 6.0.5 on 2026-06-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_privacy_settings(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserPrivacySettings = apps.get_model('accounts', 'UserPrivacySettings')
    UserPrivacySettings.objects.bulk_create([
        UserPrivacySettings(user=user)
        for user in User.objects.all()
        if not UserPrivacySettings.objects.filter(user=user).exists()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_keytrust'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_visibility', models.CharField(default='everyone', max_length=20)),
                ('profile_photo_visibility', models.CharField(default='everyone', max_length=20)),
                ('phone_number_visibility', models.CharField(default='contacts', max_length=20)),
                ('bio_visibility', models.CharField(default='everyone', max_length=20)),
                ('forward_link_visibility', models.CharField(default='everyone', max_length=20)),
                ('who_can_send_messages', models.CharField(default='contacts', max_length=20)),
                ('who_can_voice_video_call', models.CharField(default='contacts', max_length=20)),
                ('auto_delete_messages_days', models.PositiveSmallIntegerField(default=0)),
                ('sensitive_content_filter', models.BooleanField(default=False)),
                ('passcode_lock_enabled', models.BooleanField(default=False)),
                ('two_step_verification_enabled', models.BooleanField(default=False)),
                ('login_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block')],
            },
        ),
        migrations.RunPython(create_default_privacy_settings, migrations.RunPython.noop),
    ]
