# Generated by Django 6.0.5 on 2026-06-10 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userstoragesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline_notifications', models.BooleanField(default=True)),
                ('all_accounts_notifications', models.BooleanField(default=True)),
                ('notification_sound', models.CharField(default='default', max_length=100)),
                ('volume', models.PositiveSmallIntegerField(default=80)),
                ('message_sent_sound', models.CharField(default='default', max_length=100)),
                ('private_chat_notifications', models.BooleanField(default=True)),
                ('group_chat_notifications', models.BooleanField(default=True)),
                ('channel_notifications', models.BooleanField(default=False)),
                ('message_preview_private', models.BooleanField(default=True)),
                ('message_preview_group', models.BooleanField(default=True)),
                ('message_preview_channel', models.BooleanField(default=True)),
                ('contact_join_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
