# Generated by Django 6.0.5 on 2026-06-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_user_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprivacysettings',
            name='passcode',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='userprivacysettings',
            name='passkey_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
