# Generated by Django 6.0.5 on 2026-06-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_general_and_chat_folder_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('bot', 'Bot')], default='user', max_length=10),
        ),
    ]
