"""
Django settings for ichat_pro project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
# Set DJANGO_DEBUG=False in production environments.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

if not DEBUG and not os.environ.get('DJANGO_SECRET_KEY'):
    raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG=False.')

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-only-change-me-before-production',
)

_ALLOWED_HOSTS_RAW = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _ALLOWED_HOSTS_RAW.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'accounts',
    'chat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'ichat_pro.csp_middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ichat_pro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ichat_pro.context_processors.tailwind',
                'ichat_pro.context_processors.settings_sidebar',
            ],
        },
    },
]

WSGI_APPLICATION = 'ichat_pro.wsgi.application'
ASGI_APPLICATION = 'ichat_pro.asgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# In production, set DATABASE_URL=postgres://USER:PASSWORD@HOST:PORT/NAME
_DATABASE_URL = os.environ.get('DATABASE_URL', '')
_SQLITE_OPTIONS = {
    # WebSocket read receipts can trigger several short writes at once during
    # local development. Give SQLite time to wait for the active writer.
    'timeout': 20,
}
if _DATABASE_URL:
    import re as _re
    _m = _re.match(
        r'^(?P<engine>postgres|postgresql|mysql)://'
        r'(?P<user>[^:]+):(?P<password>[^@]+)@'
        r'(?P<host>[^:/]+):?(?P<port>\d+)?/(?P<name>.+)$',
        _DATABASE_URL,
    )
    if _m:
        _engine_map = {
            'postgres': 'django.db.backends.postgresql',
            'postgresql': 'django.db.backends.postgresql',
            'mysql': 'django.db.backends.mysql',
        }
        DATABASES = {
            'default': {
                'ENGINE': _engine_map[_m.group('engine')],
                'NAME': _m.group('name'),
                'USER': _m.group('user'),
                'PASSWORD': _m.group('password'),
                'HOST': _m.group('host'),
                'PORT': _m.group('port') or '',
            }
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
                'OPTIONS': _SQLITE_OPTIONS,
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': _SQLITE_OPTIONS,
        }
    }

# Channel layer
# In production, set REDIS_URL=redis://[:password@]host:port/db
_REDIS_URL = os.environ.get('REDIS_URL', '')
if _REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [_REDIS_URL],
            },
        },
    }

    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _REDIS_URL,
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'ichat-pro-dev-cache',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

LOGIN_URL = 'login'

# Media files (user uploads like avatars)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Tailwind CSS: use Play CDN in dev, static build in production
TAILWIND_CDN = DEBUG
CSP_ALLOW_UNSAFE_INLINE_SCRIPT = os.environ.get('CSP_ALLOW_UNSAFE_INLINE_SCRIPT', 'false').lower() in (
    '1',
    'true',
    'yes',
    'on',
)
CSP_ALLOW_UNSAFE_INLINE_STYLE = os.environ.get('CSP_ALLOW_UNSAFE_INLINE_STYLE', 'true').lower() in (
    '1',
    'true',
    'yes',
    'on',
)

# =============================================================================
# Production security settings (T25)
# These are ONLY active when DEBUG=False.
# See docs/iChat Pro 部署安全说明.md for full deployment guide.
# =============================================================================
if not DEBUG:
    # Force HTTPS
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookie security
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True

    # Prevent MIME sniffing
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Prevent clickjacking (already in middleware, but belt-and-suspenders)
    X_FRAME_OPTIONS = 'DENY'

    # Referrer policy
    SECURE_REFERRER_POLICY = 'same-origin'

    # Also enable Django's built-in security checks
    SILENCED_SYSTEM_CHECKS = []

